eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9003/eureka/
  instance:
    hostname: localhost
    
    
    
ModuleName: XYZModule

msg: Git Development Environment Hello from config server.
